extends Node

const MODIFY_INTERNALS = [
	{
		"system":"SYSTEM_CARGO_AUX_STORPROC_8K",
		"storage_flat":8000
	},
	{
		"system":"SYSTEM_CARGO_AUX_STORAGE_4K",
		"storage_flat":4000,
		"storage_ammo":1500,
		"storage_nanodrones":1500,
		"storage_propellant":4000
	},
	{
		"system":"SYSTEM_CARGO_MPU_BULK",
		"storage_flat":10000
	},
	{
		"system":"SYSTEM_CARGO_AUX_FAB",
		"storage_flat":2000,
		"storage_propellant":6000
	},
	{
		"system":"SYSTEM_CARGO_AUX_BIGFAB",
		"storage_ammo":5000,
		"storage_nanodrones":5000
	},
	{
		"system":"SYSTEM_CARGO_MOD_2K",
		"storage_flat":2000,
		"mass":1000
	},
	{
		"system":"SYSTEM_CARGO_MOD_4K",
		"storage_flat":4000,
		"mass":2000
	},
	{
		"system":"SYSTEM_CARGO_MOD_6K",
		"storage_flat":6000,
		"mass":3500
	},
	{
		"system":"SYSTEM_CARGO_MOD_BOLTS",
		"storage_multi":1/1,
		"force_type":"divided",
		"mass":-650
	},
	{
		"system":"SYSTEM_CARGO_MOD_AMORPH4",
		"storage_multi_upper":1,
		"storage_multi_lower":2,
		"force_type":"amorphic",
		"mass":1500
	},
	{
		"system":"SYSTEM_CARGO_MOD_AMORPH5",
		"storage_multi_upper":2,
		"storage_multi_lower":3,
		"force_type":"amorphic",
		"mass":2500
	},
	{
		"system":"SYSTEM_CARGO_MOD_AMORPH6",
		"storage_multi_upper":5,
		"storage_multi_lower":6,
		"force_type":"amorphic",
		"mass":3750
	},
	{
		"system":"SYSTEM_CREW_ADD_BUNK",
		"crew_count":1,
		"crew_morale":-0.3
	},
	{
		"system":"SYSTEM_CREW_ADD_BUNK2",
		"crew_count":2,
		"crew_morale":-0.4
	},
	{
		"system":"SYSTEM_CREW_ADD_CAPSULE",
		"crew_count":2,
		"crew_morale":-0.25
	},
	{
		"system":"SYSTEM_CREW_MOD_HOME",
		"crew_count":0,
		"crew_morale":0.1
	},
	{
		"system":"SYSTEM_CREW_MOD_KMX",
		"crew_count":0,
		"crew_morale":0.2
	},
	{
		"system":"SYSTEM_CREW_MOD_OCM",
		"crew_count":0,
		"crew_morale":0.5
	}
]
