extends Node

const MODIFY_INTERNALS = [
	{
		"system":"SYSTEM_CARGO_AUX_STORPROC_8K",
		"storage_flat":8000
	},
	{
		"system":"SYSTEM_CARGO_AUX_STORAGE_4K",
		"storage_flat":4000,
		"storage_ammo":3000,
		"storage_nanodrones":3000,
		"storage_propellant":5000
	},
	{
		"system":"SYSTEM_CARGO_MPU_BULK",
		"storage_flat":10000
	},
	{
		"system":"SYSTEM_CARGO_AUX_FAB",
		"storage_flat":2000,
		"storage_propellant":6000
	},
	{
		"system":"SYSTEM_CARGO_AUX_BIGFAB",
		"storage_ammo":5000,
		"storage_nanodrones":5000
	},
	{
		"system":"SYSTEM_CARGO_MOD_2K",
		"storage_flat":2000,
		"mass":1600,
		"mass_per_tonne_of_processed_ore":100,
	},
	{
		"system":"SYSTEM_CARGO_MOD_4K",
		"storage_flat":4000,
		"mass":3300,
		"mass_per_tonne_of_processed_ore":100,
	},
	{
		"system":"SYSTEM_CARGO_MOD_6K",
		"storage_flat":6000,
		"mass":5500,
		"mass_per_tonne_of_processed_ore":100,
	},
	{
		"system":"SYSTEM_CARGO_MOD_BOLTS",
		"force_type":"divided",
		"mass":-2650
	},
	{
		"system":"SYSTEM_CARGO_MOD_AMORPH4",
		"storage_multi_upper":1,
		"storage_multi_lower":2,
		"force_type":"amorphic",
		"mass_per_tonne_total_storage_added":-20,
		"mass":1500
	},
	{
		"system":"SYSTEM_CARGO_MOD_AMORPH5",
		"storage_multi_upper":2,
		"storage_multi_lower":3,
		"force_type":"amorphic",
		"mass_per_tonne_total_storage_added":-75,
		"mass":2500
	},
	{
		"system":"SYSTEM_CARGO_MOD_AMORPH6",
		"storage_multi_upper":5,
		"storage_multi_lower":6,
		"force_type":"amorphic",
		"mass_per_tonne_total_storage_added":-165,
		"mass":3750
	},
	{
		"system":"SYSTEM_CREW_ADD_BUNK",
		"crew_count":1,
		"crew_morale":-0.3,
		"mass":250,
		"mass_per_crew_member":15
	},
	{
		"system":"SYSTEM_CREW_ADD_BUNK2",
		"crew_count":2,
		"crew_morale":-0.4,
		"mass":500,
		"mass_per_crew_member":35
	},
	{
		"system":"SYSTEM_CREW_ADD_CAPSULE",
		"crew_count":2,
		"crew_morale":-0.25,
		"mass":1000,
		"mass_per_crew_member":60
	},
	{
		"system":"SYSTEM_CREW_MOD_HOME",
		"crew_count":0,
		"crew_morale":0.1,
		"mass":200,
		"mass_per_crew_member":75
	},
	{
		"system":"SYSTEM_CREW_MOD_KMX",
		"crew_count":-1,
		"crew_morale":0.2,
		"mass":500,
		"mass_per_crew_member":150
	},
	{
		"system":"SYSTEM_CREW_MOD_OCM",
		"crew_count":-2,
		"crew_morale":0.5,
		"mass":700,
		"mass_per_crew_member":200
	},
	{
		"system":"SYSTEM_HULLVAT_AMMO_1",
		"storage_ammo":6000,
		"crew_morale":-0.05,
		"nano_multi_upper":3,
		"nano_multi_lower":4,
		"mass":3000,
	},
	{
		"system":"SYSTEM_HULLVAT_AMMO_2",
		"storage_ammo":15000,
		"crew_morale":-0.1,
		"nano_multi_upper":1,
		"nano_multi_lower":2,
		"mass":10000,
	},
	{
		"system":"SYSTEM_HULLVAT_AMMO_EXTEND_1",
		"ammo_multi_upper":4,
		"ammo_multi_lower":3,
		"storage_ammo":1000,
		"storage_multi_upper":9,
		"storage_multi_lower":10,
		"mass":9000,
	},
	{
		"system":"SYSTEM_HULLVAT_AMMO_EXTEND_2",
		"ammo_multi_upper":5,
		"ammo_multi_lower":3,
		"storage_ammo":2000,
		"storage_multi_upper":4,
		"storage_multi_lower":5,
		"mass":20000,
	},
	{
		"system":"SYSTEM_HULLVAT_AMMO_EXTEND_3",
		"ammo_multi_upper":2,
		"ammo_multi_lower":1,
		"storage_ammo":1000,
		"propellant_multi_upper":2,
		"propellant_multi_lower":3,
		"mass":35000,
	},
	{
		"system":"SYSTEM_HULLVAT_NANO_1",
		"storage_nano":6000,
		"crew_morale":-0.05,
		"ammo_multi_upper":3,
		"ammo_multi_lower":4,
		"mass":4500,
	},
	{
		"system":"SYSTEM_HULLVAT_NANO_2",
		"storage_nano":15000,
		"crew_morale":-0.1,
		"ammo_multi_upper":1,
		"ammo_multi_lower":2,
		"mass":12000,
	},
	{
		"system":"SYSTEM_HULLVAT_NANO_EXTEND_1",
		"nano_multi_upper":4,
		"nano_multi_lower":3,
		"storage_nano":1000,
		"storage_multi_upper":9,
		"storage_multi_lower":10,
		"mass":10500,
	},
	{
		"system":"SYSTEM_HULLVAT_NANO_EXTEND_2",
		"nano_multi_upper":5,
		"nano_multi_lower":3,
		"storage_nano":2000,
		"storage_multi_upper":4,
		"storage_multi_lower":5,
		"mass":25000,
	},
	{
		"system":"SYSTEM_HULLVAT_NANO_EXTEND_3",
		"nano_multi_upper":2,
		"nano_multi_lower":1,
		"storage_nano":1000,
		"propellant_multi_upper":2,
		"propellant_multi_lower":3,
		"mass":40000,
	},
	{
		"system":"SYSTEM_HULLVAT_PROP_1",
		"storage_propellant":10000,
		"storage_multi_upper":7,
		"storage_multi_lower":8,
		"mass":1500,
	},
	{
		"system":"SYSTEM_HULLVAT_PROP_2",
		"storage_propellant":25000,
		"storage_multi_upper":3,
		"storage_multi_lower":4,
		"mass":4000,
	},
	{
		"system":"SYSTEM_HULLVAT_PROP_EXTEND_1",
		"propellant_multi_upper":5,
		"propellant_multi_lower":4,
		"nano_multi_upper":7,
		"nano_multi_lower":8,
		"ammo_multi_upper":7,
		"ammo_multi_lower":8,
		"mass":3000,
	},
	{
		"system":"SYSTEM_HULLVAT_PROP_EXTEND_2",
		"propellant_multi_upper":3,
		"propellant_multi_lower":2,
		"nano_multi_upper":6,
		"nano_multi_lower":8,
		"ammo_multi_upper":6,
		"ammo_multi_lower":8,
		"mass":8000,
	},
	{
		"system":"SYSTEM_HULLVAT_PROP_EXTEND_3",
		"propellant_multi_upper":7,
		"propellant_multi_lower":4,
		"nano_multi_upper":5,
		"nano_multi_lower":8,
		"ammo_multi_upper":5,
		"ammo_multi_lower":8,
		"mass":15000,
	},
	{
		"system":"SYSTEM_HULLVAT_CONSUMABLESPEED_1",
		"ammo_speed_multi_upper":3,
		"ammo_speed_multi_lower":2,
		"mass":3800,
	},
	{
		"system":"SYSTEM_HULLVAT_CONSUMABLESPEED_2",
		"ammo_speed_multi_upper":2,
		"ammo_speed_multi_lower":1,
		"crew_morale":-0.1,
		"mass":9000,
	},
]
