extends Node

const SHIP_TRTL = {
	"ship_name":"SHIP_TRTL",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-28,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_TRTL_LCB = {
	"ship_name":"SHIP_TRTL_LCB",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_TRTL_K44 = {
	"ship_name":"SHIP_TRTL_K44",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_PROSPECTOR_LUX = {
	"ship_name":"SHIP_PROSPECTOR_LUX",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_COTHON_V = {
	"ship_name":"SHIP_COTHON_V",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_COTHON_LND = {
	"ship_name":"SHIP_COTHON_LND",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_COTHON_CHK = {
	"ship_name":"SHIP_COTHON_CHK",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_OCP209_DD = {
	"ship_name":"SHIP_OCP209_DD",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
		"IOE_OCP_DOCKING_BAY_UPPER":{},
		"IOE_OCP_DOCKING_BAY_LOWER":{},
		"IOE_OCP_DRONE_BAY_UPPER":{},
		"IOE_OCP_DRONE_BAY_LOWER":{},
	}
}

const SHIP_OCP213_TWIN = {
	"ship_name":"SHIP_OCP213_TWIN",
	"node_definitions":{
		"IOE_OCP_DOCKING_BAY_UPPER":{},
		"IOE_OCP_DOCKING_BAY_LOWER":{},
		"IOE_OCP_TURRET_BAY_UPPER":{},
		"IOE_OCP_TURRET_BAY_LOWER":{},
	}
}

const SHIP_OCP209_SNAP = {
	"ship_name":"SHIP_OCP209_SNAP",
	"node_definitions":{
		"IOE_OCP_DOCKING_BAY_UPPER":{},
		"IOE_OCP_DOCKING_BAY_LOWER":{},
		"IOE_OCP_DRONE_BAY_UPPER":{},
		"IOE_OCP_DRONE_BAY_LOWER":{},
	}
}

const SHIP_OCP_SALVAGE = {
	"ship_name":"SHIP_OCP-SALVAGE",
	"node_definitions":{
		"IOE_OCP_TURRET_BAY_UPPER":{
			"properties":{
				"toggleCommand":{
					"value":"ship_slot_5"
				}
			}
		},
		"IOE_OCP_TURRET_BAY_LOWER":{
			"properties":{
				"toggleCommand":{
					"value":"ship_slot_6"
				}
			}
		},
		"IOE_OCP_DRONE_BAY_UPPER":{},
		"IOE_OCP_DRONE_BAY_LOWER":{},
	}
}

const SHIP_MADCERF_CIV = {
	"ship_name":"SHIP_MADCERF_CIV",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_AT225_STUB = {
	"ship_name":"SHIP_AT225_STUB",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_COTHON_LUX = {
	"ship_name":"SHIP_COTHON_LUX",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_TRTL_RAM = {
	"ship_name":"SHIP_TRTL_RAM",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_PROSPECTOR = {
	"ship_name":"SHIP_PROSPECTOR",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-23,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_PROSPECTOR_VP = {
	"ship_name":"SHIP_PROSPECTOR_VP",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-23,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_AT225 = {
	"ship_name":"SHIP_AT225",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-32,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-32,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-28,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-32,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-32,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-32,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-32,-210]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_AT225B = {
	"ship_name":"SHIP_AT225B",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.85]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.45]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-46,-201],
				"scale":[1.5]
			},
			"properties":{
				"polygon":{
					"value":[0,-32,10,-28,8,-12,2,-8,8,-6,10,0,8,6,2,8,8,12,10,28,8,32,-4,32,-23.3,19.3,-4,19.3,-4,-23.3,-14,-42.6],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.2]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.4]
			},
			"properties":{
				"polygon":{
					"value":[0,32,-12.1,20.7,0,8,0,-22.1,-5.71,-32.1,10,-32,20,-28,20,4,10,8,10,20],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-50,-201]
			},
			"properties":{
				"polygon":{
					"value":[-4,-48,28,-12,32,-4,32,30,18,30,10,40,10,52,0,64,-51,29,0,29],
					"method":"arr2vec2arr"
				}
			}
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-50,-201]
			},
			"properties":{
				"polygon":{
					"value":[-4,-35,16,-34,32,-28,32,38,24,40,18,40,16,46,10,48,10,60,0,72,-61,70,-78,28,-1,26],
					"method":"arr2vec2arr"
				}
			}
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-50,-201],
				"scale":[2.5]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-50,-201],
				"scale":[3]
			},
			"properties":{
				"polygon":{
					"value":[0,19,-26,9.66,0,9.66,0,-10.3,5,1,6,13],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-50,-201],
				"scale":[3]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_AT225R = {
	"ship_name":"SHIP_AT225R",
	"node_definitions":{
		"IOE_BAY_AUX_PERSIST":{},
	}
}

const SHIP_PROSPECTOR_FAT = {
	"ship_name":"SHIP_PROSPECTOR_FAT",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-36,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_OCP209 = {
	"ship_name":"SHIP_OCP209",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"polygon":{
					"value":[0,25,0,-25,16,-12,12,-4,12,4,16,12]
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-136,0],
				"scale":[1.5]
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
			},
			"properties":{
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
			},
			"properties":{
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-140,0],
				"scale":[1],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_OCP_DOCKING_BAY_UPPER":{},
		"IOE_OCP_DOCKING_BAY_LOWER":{},
		"IOE_OCP_TURRET_BAY_UPPER":{},
		"IOE_OCP_TURRET_BAY_LOWER":{},
	},
}

const SHIP_COTHON = {
	"ship_name":"SHIP_COTHON",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-43,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-43,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-39,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-43,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-43,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-43,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-43,-188]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_TRTL_OCP = {
	"ship_name":"SHIP_TRTL_OCP",
	"fallback_to_base_ship":false,
	"fallback_override":"SHIP_TRTL",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"polygon":{
					"value":[0,25,0,-25,16,-12,12,-4,12,4,16,12],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-136,0],
				"scale":[1.5]
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
			},
			"properties":{
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
			},
			"properties":{
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-140,0],
				"scale":[1],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
			},
			"properties":{
				"mirrorVertical":{
					"value":true
				},
				"ProcessingArea/ZoneTop/polygon":{
					"value":[244, 0, 238, -34, 223, -64, 198, -95, 180, -112, 161, -122, 139, -129, 109, -132, 86, -129, 59, -123, 35, -109, 12, -91, -8, -66, -22, -34, -26, 0],
					"method":"arr2vec2arr"
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"value":[244, 0, 238, 34, 223, 64, 198, 95, 161, 122, 109, 132, 56, 122, 12, 91, -8, 66, -22, 34, -26, 0],
					"method":"arr2vec2arr"
				},
				"set_rot":{
					"value":45
				}
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_TSUKUYOMI_IOT = {
	"ship_name":"SHIP_TSUKUYOMI_IOT",
	"fallback_to_base_ship":false,
	"fallback_override":"SHIP_TSUKUYOMI_IOT",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-113,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}

const SHIP_PROSPECTOR_PIGEON = {
	"ship_name":"SHIP_PROSPECTOR_PIGEON",
	"fallback_to_base_ship":true,
	"fallback_override":"SHIP_PROSPECTOR",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-36,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
			"properties":{
				"ProcessingArea/ZoneBottom/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneTop/position":{
					"method":"center_to_ship",
					"ignore_scaling":true
				},
				"ProcessingArea/ZoneBottom/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneTop/polygon":{
					"method":"copy",
					"node_path":"CargoHoldArea/CollisionPolygon2D"
				},
				"ProcessingArea/ZoneBottom/scale":{
					"method":"invert_scaling",
				},
				"ProcessingArea/ZoneTop/scale":{
					"method":"invert_scaling",
				},
			}
		},
		"IOE_BAY_AUX_PERSIST":{},
	},
}
