extends Node

const SHIP_TRTL = {
	"ship_name":"SHIP_TRTL",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-28,-75],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-32,-75],
				"scale":[0.8]
			},
		},
	},
}

const SHIP_TSUKUYOMI_IOT = {
	"ship_name":"SHIP_TSUKUYOMI_IOT",
	"fallback_to_base_ship":false,
	"fallback_override":"SHIP_TSUKUYOMI_IOT",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-113,-1125],
				"scale":[2]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-117,-1125],
				"scale":[2]
			},
		},
	},
}

const SHIP_PROSPECTOR = {
	"ship_name":"SHIP_PROSPECTOR",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-23,-192],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-27,-192],
				"scale":[0.8]
			},
		},
	},
}

const SHIP_PROSPECTOR_VP = {
	"ship_name":"SHIP_PROSPECTOR_VP",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-23,-130],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-27,-130],
				"scale":[0.8]
			},
		},
	},
}

const SHIP_AT225 = {
	"ship_name":"SHIP_AT225",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-28,-210]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-32,-210]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-32,-210]
			},
		},
	},
}

const SHIP_AT225B = {
	"ship_name":"SHIP_AT225B",
	"fallback_to_base_ship":true,
	"fallback_override":"SHIP_AT225",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.85]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.45]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-46,-201],
				"scale":[1.5]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.2]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-50,-201],
				"scale":[1.4]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-50,-201]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-50,-201]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-50,-201],
				"scale":[2.5]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-50,-201],
				"scale":[3]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-50,-201],
				"scale":[3]
			},
		},
	},
}

const SHIP_PROSPECTOR_FAT = {
	"ship_name":"SHIP_PROSPECTOR_FAT",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-36,-230],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-40,-230],
				"scale":[0.8]
			},
		},
	},
}

const SHIP_PROSPECTOR_PIGEON = {
	"ship_name":"SHIP_PROSPECTOR_PIGEON",
	"fallback_to_base_ship":true,
	"fallback_override":"SHIP_PROSPECTOR",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-36,-165],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-40,-165],
				"scale":[0.8]
			},
		},
	},
}

const SHIP_OCP209 = {
	"ship_name":"SHIP_OCP209",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":45,
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":45,
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-136,0],
				"scale":[1.5],
				"rotation":45,
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":45,
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":45,
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
				"rotation":45,
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
				"rotation":45,
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-140,0],
				"scale":[1],
				"rotation":45,
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
				"rotation":45,
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
				"rotation":45,
			},
		},
	},
}

const SHIP_TRTL_OCP = {
	"ship_name":"SHIP_TRTL_OCP",
	"fallback_to_base_ship":true,
	"fallback_override":"SHIP_OCP209",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":190,
			},
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":190,
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-136,0],
				"scale":[1.5],
				"rotation":190,
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":190,
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-140,0],
				"scale":[1.75],
				"rotation":190,
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
				"rotation":190,
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-140,0],
				"scale":[0.8],
				"rotation":190,
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-140,0],
				"scale":[1],
				"rotation":190,
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
				"rotation":190,
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-140,0],
				"scale":[2],
				"rotation":190,
			},
		},
	},
}

const SHIP_COTHON = {
	"ship_name":"SHIP_COTHON",
	"node_definitions":{
		"IOE_PREPROC_0x30":{
			"position_data":{
				"position":[-43,-188]
			}
		},
		"IOE_PREPROC_20x10":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_PREPROC_40x20":{
			"position_data":{
				"position":[-39,-188]
			},
		},
		"IOE_STORAGE_4K":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_STORAGE_8K":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_FABAUX_FAB":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_FABAUX_BIGFAB":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_ICEBREAKER_M35":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_ICEBREAKER_M85":{
			"position_data":{
				"position":[-43,-188]
			},
		},
		"IOE_ICEBREAKER_P15":{
			"position_data":{
				"position":[-43,-188]
			},
		},
	},
}
